### ISSUE TITLE
When on null

### ISSUE THREAD

**Issue by retsu8** [battlecode/battlecode-scaffold#4]
init:

build:

run:
     [java] [server:warning] Couldn't load map null, skippingjava.io.IOException: Can't load map: null from dir maps or default maps.
     [java] [server:warning] java version "1.8.0_65"
     [java] 
     [java]     at battlecode.world.GameMapIO.loadMap(GameMapIO.java:58)
     [java]     at battlecode.server.Server.runMatch(Server.java:283)
     [java]     at battlecode.server.Server.run(Server.java:232)
     [java]     at java.lang.Thread.run(Thread.java:745)
     [java] [server:warning] OpenJDK 64-Bit Server VM (build 25.65-b01, mixed mode)
     [java] [server:warning] Please report this to the 6.370 devs, by posting to the forum
     [java] [server:warning] under the "bugs" thread.  Include a copy of this printout and
     [java] [server:warning] a brief description of the bug, including whether it's consistent
     [java] [server:warning] or sporadic.  Thanks!

When a map is loaded with the null attribute instead of just skipping the map it crashes the builder.

**Comment by kazimuth** [comment]
This is an issue with battlecode-client, not battlecode-scaffold:
[#92](https://github.com/battlecode/battlecode-client/issues/92)
