### ISSUE TITLE
Ways to share code between different versions of bots

### ISSUE THREAD

**Issue by ichaelm** [battlecode/battlecode-scaffold#5]
I've been revisiting the challenge from last year to see if I could make changes to the scaffold that would allow me to share code between different versions of my bot, and have the client and server be able to play them against each other. My first attempt was to edit build.xml to split the build step into two steps: build-core and build-variations. The build-core task builds files in one player_core package, and the build-variations task builds files in each player package.

I got the build step to work, but when I try to run my bots in the client, I end up with exceptions in the server caused by the package whitelist. I didn't think about the fact that allowing players to contain code in multiple packages would be a problem. So now the only way I can think of to do this is to make build.xml copy the shared core files into the player package directories and edit each file's package declaration. Is there a better way?

**Comment by kazimuth** [comment]
Right now, no, but this is a good point. We can extend the instrumentation to allow multiple packages in player bots. The only reason it doesn't currently is because of legacy architecture stuff, which should be fixable.
